# Configuracion comun a master / worker / driver lanzado desde Airflow
spark.master                                        spark://spark-master:7077

# ---- Integracion con MinIO (S3A) ------------------------------------------------
spark.hadoop.fs.s3a.impl                            org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.endpoint                        http://minio:9000
spark.hadoop.fs.s3a.access.key                      minioadmin
spark.hadoop.fs.s3a.secret.key                      minioadmin
spark.hadoop.fs.s3a.path.style.access               true
spark.hadoop.fs.s3a.connection.ssl.enabled          false
spark.hadoop.fs.s3a.aws.credentials.provider        org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
spark.hadoop.fs.s3a.fast.upload                     true

# Jars Necesarios para escribir en S3 (se descargan la primera vez via ivy)
spark.jars.packages                                 org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262
# /tmp porque el driver corre en el contenedor de Airflow como UID 50000,
# que no puede escribir en /root/.ivy2 (Permission denied en spark-submit).
spark.jars.ivy                                      /tmp/.ivy2

# ---- Formato columnar -----------------------------------------------------------
spark.sql.parquet.compression.codec                 snappy
spark.sql.sources.partitionOverwriteMode             dynamic
spark.sql.parquet.datetimeRebaseModeInWrite          CORRECTED

# ---- Rendimiento / estabilidad en entorno con poca RAM --------------------------
spark.executor.memory                               1g
spark.executor.cores                                1
spark.driver.memory                                 1g
spark.sql.shuffle.partitions                        8
spark.sql.adaptive.enabled                          true

# Java 17 necesita abrir modulos internos a Spark
spark.driver.extraJavaOptions                       --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED -Dio.netty.tryReflectionSetAccessible=true
spark.executor.extraJavaOptions                     --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED -Dio.netty.tryReflectionSetAccessible=true
