apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: streaming_metrics
    user: streaming_user
    secureJsonData:
      password: streaming_pass
    jsonData:
      sslmode: "disable"
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      timescaledb: false
    editable: false

  - name: MinIO (S3)
    type: grafana-s3-datasource
    access: proxy
    url: http://minio:9000
    jsonData:
      bucket: metrics
      region: us-east-1
      accessKey: minioadmin
      secretKey: minioadmin123
      endpoint: http://minio:9000
    editable: false